font_family JetBrains Mono
font_size 13

confirm_os_window_close 0

background_opacity 0.78
background_blur 1

# --- Colors ---

# The basic colors
foreground              #CAB6CD
background              #0A0908
selection_foreground    #0A0908
selection_background    #9A4C95

# Cursor colors
cursor                  #9A4C95
cursor_text_color       #0A0908

# URL underline color when hovering with mouse
url_color               #9A4C95

# Kitty window border colors
active_border_color     #9A4C95
inactive_border_color   #0A0908

# Tab bar colors
active_tab_foreground   #0A0908
active_tab_background   #9A4C95
inactive_tab_foreground #CAB6CD
inactive_tab_background #0A0908

# The 16 terminal colors


# Red (using accent tones)
color1 #9A4C95
color9 #B36BAE

# Green
color2 #9A4C95
color10 #B36BAE

# Yellow
color3 #CAB6CD
color11 #E3D5E5

# Blue
color4 #9A4C95
color12 #B36BAE

# Magenta
color5 #9A4C95
color13 #B36BAE

# Cyan
color6 #CAB6CD
color14 #E3D5E5

# White
color7 #CAB6CD
color15 #FFFFFF
